### ISSUE TITLE
Write Access

### ISSUE THREAD

**Issue by foxcqrn** [EmeraldFreedom/EmeraldFreedomMod#2]
I do not have write access.

**Comment by DUFCLiam** [comment]
You have not been allocated by: @rovertdude

**Comment by DUFCLiam** [comment]
This was a bug when I was configuring permissions! Fixed.

**Comment by rovertdude** [comment]
@DUFCLiam @FoxIshDaBest 

The EmeraldFreedomMod wasn't supposed to fully be for this - it was made for a friend of mine just to rename the plugin to EmeraldFreedomMod.

**Comment by foxcqrn** [comment]
Oh

**Comment by DUFCLiam** [comment]
I have discontinued `PugFreedomMod` would you like it to be reinstated as a current project?

**Comment by DUFCLiam** [comment]
@FoxIshDaBest @rovertdude

**Comment by foxcqrn** [comment]
I don't know. I am going to try updating RainbowFreedom to 1.9 and RFM to 5.0. I already updated FreedomBot to 2.0 so now I just need to finish the RFMv2 plugin.

**Comment by foxcqrn** [comment]
You guys want to help?
@DUFCLiam @rovertdude

**Comment by DUFCLiam** [comment]
@FoxIshDaBest, Sure!

OFT: Can you add me to HTML team?

**Comment by foxcqrn** [comment]
Sure. That means you will work on the website aswell

**Comment by foxcqrn** [comment]
Added @DUFCLiam 
At school I'm spposed to be doing some essay atm,
#straightsavage

**Comment by DUFCLiam** [comment]
@FoxIshDaBest Just do the essay then come back! :P

**Comment by foxcqrn** [comment]
No c:

**Comment by foxcqrn** [comment]
I'll do it later

**Comment by DUFCLiam** [comment]
Haha You better remember to do it!

**Comment by foxcqrn** [comment]
Alright I gtg I'm switching classes

**Comment by foxcqrn** [comment]
Alright back @DUFCLiam
